- name: print the var from file
  hosts: anisble_node_private_IP
  vars_file:
  - vars.yml
  tasks:
  - name: print the variables form vars file
    ansible.builtin.debug:
      msg: "Hi i am learning {{Course}}, duration is {{Duration}}, trainer by {{Trainer}}"