- name: check the given details of conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: enter the number 
    private: false #not confidential
  tasks:
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "given number {{number}} is less than 10"
    when: number < 10 # conditional expression

  - name: print this if greater than 10
    ansible.builtin.debug:
      msg: "given number {{number}} is greter than or equals to 10"
    when: number >= 10
