#google using filters to manipulate data-> handling undefined variables,uppercase,lower,unique,min and max,convert map to list/list to map,IP address filter

- name: filter in ansible
  hosts: local
  connection: local
  tasks:
  - name: varibale not defined
    ansible.builtin.debug:
     msg: "{{course | default ('ansible')}}"   #here course variable has not defind so in ansible by using default filter we can achieve varibales




