- name: creating ec2 and r53
  hosts: local
  connection: local
  vars:
   subnet_id: "subnet-09ca74174dd671a63"
   sg_id: "sg-04de82942b1f8408d"
   image_id: "ami-09c813fb71547fc4f" 
   instance:
    -frontend
    -backend
    -mysql
  -name: creating ec2 instances
  amazon.aws.ec2_instance:
    name: item
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: "{{ sg_id }}"
    image_id: "{{image_id}}"
    instance_type: "t3.micro"

  loop: "{{instance}}"

